var GAME_LEVELS = [
  ["                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "  xxxxxxx                              xxx                                      ",
   "  x                        o                                             xxxxx  ",
   "  x                    o      xxx         o o                                x  ",
   "  x                o                        x!!!x                            x  ",
   "  x                                         x!!!x                            x  ",
   "  x          xyyx                         xxxxxxxxx                    o  o  x  ",
   "  x  @       x  x                                                xxxxx o  o  x  ",
   "  xxxxxxxxxxxx  xxxxxxxxxxxx      xxxxxxxyyyyyxxxxxxx       xxxxxx   xxxxxxxxx  ",
   "                           x   o  xxxxxxx     xxxxxxx      ox                   ",
   "                           x      xxxxxxx     xxxxxxx       x                   ",
   "                           x   o  xxxxxxxxxxxxxxxxxxxxxx    x                   ",
   "                           x                                x                   ",
   "                           x   o                          xxx                   ",
   "                           x                                x                   ",
   "                           x      x    =      o     x       x                   ",
   "                           xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                   ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                ",
   "                                                                                "],
  ["                                                             xxx!!!!!!!!!!!xxx                   ",
   "                                                              xx!!!!!!!!!!!xx                    ",
   "                                                               xxxxxxvxxxxxx                     ",
   "                                               x  o   x                                          ",
   "                                               x      x                                          ",
   "                                               x  o   x                                          ",
   "                                               x                                                 ",
   "                                         xxx   x                                                 ",
   "                                               xxx           o  o                     o          ",
   "               xxxxxxxxx                       x                                     o o         ",
   "              xxxxxxxxxx         x   x         x      x     xxxxxx    x   x!!!xxxxxxxyyyxxxxxxx  ",
   "             xx       xx         x o x         x    xxx               x   x!!!x               x  ",
   "     @       x         x         x   x         x      x               x   x!!!x       o       x  ",
   "    xxx      x         x       xxx   x         x      x               x   xxxxx     xxxxx     x  ",
   "    x x      x         x   o   xxx o xx!!!!!!!!x      x               x     o       xx        x  ",
   "!!!!x x!!!!!!x         xxxxxxxxx     xxxxxxxxxxxxx    x               x     =       xx        x  ",
   "!!!!x x!!!!!!x         x!!!!!xx                       x!!!!!!!xx      xxxxxxxxxxxxxxxx o o  xxx  ",
   "!!!!x x!!!!!!x         x!!!!!x     o                 xx!!!!!!xx                      x     xxxx  ",
   "!!!!x x!!!!!!x         x!!!!!x                     xx!!!!!!xx                        xxxxxxxxxx  ",
   "!!!!x x!!!!!!x         x!!!!!xx       xxxxxxxxxxxxxx!!!!!!xx                                     ",
   "!!!!x x!!!!!!x         x!!!!!!xxxxxxxxx!!!!!!!!!!!!!!!!!!xx                                      ",
   "!!!!x x!!!!!!x         x!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!xx                                       "],
  ["                                                                   x!!!!!!!x                          ",
   "                                                    o              xxxxvxxxx                          ",
   "                                                       x!!!x                  x!!!x                   ",
   "                 x                        ====x         xxx                   xxvxx                   ",
   "                                                                                                      ",
   "                                  xxxx             xx         o                                       ",
   "                                                                                                      ",
   "  x                          xxx!!!!!!!!!xxx             o          o                            xxx  ",
   "  x                          xxxxxxxxxxxxxxx                                     o               xxx  ",
   "  x                          x             x   xxxxxxxxyyyyxxxxxxxxxxx      xxxxxxxxx            xxx  ",
   "  x                  xxxx    x                     xx!!!!!!!xx                                   xxx  ",
   "  x                          xxxxxxx                 xxxx!xxxx                                   xxx  ",
   "  x                            x                         v                                       xxx  ",
   "  xxx          xxxx            x        xxxxxxx                        xxxxxx                 o  xxx  ",
   "  x    o                       x         x                              x   x                    xxx  ",
   "  x    o                       x         x                              x!!!x                    xxx  ",
   "  x    o                       xxxx      x           yyyy            xxxxxxxx o                  xxx  ",
   "  xxxxxxxxxxxyyyyyxxxxx        x         x                                   xxx!!!xxxx        o xxx  ",
   "  xxxxxxxxxxx  o  xxxxx     o xx         x                                   xxxxxxxxxxx       xxxxx  ",
   "  xxxxxxxxxxx               xxxx         x    x x      xxx                                   xxxxxxx  ",
   "  x                        xxxxxxxxxxxxxxx oo x     oo x       oo  xxxxxxx     o o o o o         xxx  ",
   "  x      @                 xxxx          x    x!!!x    x!!!!x    xxxxxxxxx                       xxx  ",
   "  xxxxxxxxxxxxxxxxxxxxxxxxxxxxx          xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx  ",
   "                                                                                                      ",
   "                                                                                                      "],
  ["                                                                                                               ",
   "                                                                                                               ",
   "                o             yyy                                                                              ",
   "    @                      yyyyyyyy               xxxxxxxxxxxxxxxxxxxxxxxxx      xxxxxxxxxxxxxxxxxxyyyyxxxxxxxx",
   " xxxxxxxxx                                                    x           x      x                           x ",
   " x                                           xxx              xx ===                                         x ",
   " x                                                            x                                              x ",
   " x               xxxxx                 xxxx                   x             xxxxx            xxxx         xxxx ",
   " x                                                            x        xxyyxx   xxxxx           x            x ",
   " x                                                            x        x            x           x            x ",
   " x                        xxx       xxx                       x        x!!!!!!!!!!!!x    xxx    x            x ",
   " x                          x!!!!!!!x            xxxxxx       x        x!!!!!!!!!!!!x           x            x ",
   " x                          xxxxxxxxx                         x        xxxxxxxxxxxxxx           xxxxx   o    x ",
   " x     xxxx                                                   x                                              x ",
   " x                                                            x           o       o                          x ",
   " x                                                            x                                         o    x ",
   " x    =            =                            =             x        xxxxxxxxxxxxxyyyxxxxxxxxxxxxxx        x ",
   " x xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx                                              x ",
   "                                     x                                                                  o    x ",
   "                                     x                                                                       x ",
   "                                     x                 o                                         xxxxxxxxyyyxx ",
   "                                     x                         xxxxxxxxxxxxx                                 x ",
   "                                     x   o  xxxxx                                                            x ",
   "                                     x                                                                       x ",
   "                                     x                                                                       x ",
   "                                     xxx                                |xxx|                  |xxx|         x ",
   "                                     x                  o                                                    x ",
   "                                     x    xxxxxxxxxx                                                         x ",
   "                                     x!!!!x        xxxxxxxxx                        o                   o    x ",
   "                                                           xxxxxxxx                                          x ",
   "                                                                  x        o                 o               x ",
   "                                                                  x                                          x ",
   "                                                                  xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx "],
];

if (typeof module != "undefined" && module.exports)
  module.exports = GAME_LEVELS;
